import EffectControlView from "./EffectControlView";
import DistortionView from "./Groups/DistortionView";
import VibratoView from "./Groups/VibratoView";

export default function EffectsView() {
  return (
    <>
      <h1>Efectos de sonido (activa como maximo 3)</h1>

      {/* https://tonejs.github.io/docs/r13/Distortion */}
      <EffectControlView name="distortion" controls={DistortionView} />
      <EffectControlView name="vibrato" controls={VibratoView} />

      {/* https://tonejs.github.io/docs/r13/Reverb */}
      {/* https://tonejs.github.io/docs/r13/Vibrato */}
      {/* https://tonejs.github.io/docs/r13/Chorus */}
      {/* https://tonejs.github.io/docs/r13/Tremolo */}
      {/* https://tonejs.github.io/docs/r13/FeedbackDelay */}
      {/* https://tonejs.github.io/docs/r13/Phaser */}
      {/* https://tonejs.github.io/docs/r13/EQ3 */}
      {/* https://tonejs.github.io/docs/r13/Compressor */}
      {/* https://tonejs.github.io/docs/r13/AutoWah */}
      {/* <EffectControlView
        name="reverb"
        label="Reverberación"
        checked={effects.reverb?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="reverb"
              property="decay"
              label="Decaimiento"
              value={effects.reverb?.decay}
              handleChange={handleChange}
              min={REVERB_DECAY_MIN}
              max={REVERB_DECAY_MAX}
              step={REVERB_DECAY_STEP}
              unit={REVERB_DECAY_UNIT}
            />

            <SliderControlView
              name="reverb"
              property="preDelay"
              label="Pre-retardo"
              value={effects.reverb?.preDelay}
              handleChange={handleChange}
              min={REVERB_PREDELAY_MIN}
              max={REVERB_PREDELAY_MAX}
              step={REVERB_PREDELAY_STEP}
              unit={REVERB_PREDELAY_UNIT}
            />

            <SliderControlView
              name="reverb"
              property="wet"
              label="Mezcla"
              value={effects.reverb?.wet}
              handleChange={handleChange}
              min={REVERB_WET_MIN}
              max={REVERB_WET_MAX}
              step={REVERB_WET_STEP}
              unit={REVERB_WET_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="vibrato"
        label="Vibración"
        checked={effects.vibrato?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="vibrato"
              property="frequency"
              label="Frecuencia"
              value={effects.vibrato?.frequency}
              handleChange={handleChange}
              min={VIBRATO_FREQUENCY_MIN}
              max={VIBRATO_FREQUENCY_MAX}
              step={VIBRATO_FREQUENCY_STEP}
              unit={VIBRATO_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="vibrato"
              property="depth"
              label="Profundidad"
              value={effects.vibrato?.depth}
              handleChange={handleChange}
              min={VIBRATO_DEPTH_MIN}
              max={VIBRATO_DEPTH_MAX}
              step={VIBRATO_DEPTH_STEP}
              unit={VIBRATO_DEPTH_UNIT}
            />
            <DropdownControlView
              name="vibrato"
              property="type"
              label="Tipo"
              value={effects.vibrato?.type}
              handleChange={handleChange}
              options={[
                VIBRATO_TYPE_SINE,
                VIBRATO_TYPE_SQUARE,
                VIBRATO_TYPE_TRIANGLE,
                VIBRATO_TYPE_SAWTOOTH,
              ]}
            />
            <SliderControlView
              name="vibrato"
              property="maxDelay"
              label="Retardo Máximo"
              value={effects.vibrato?.maxDelay}
              handleChange={handleChange}
              min={VIBRATO_MAX_DELAY_MIN}
              max={VIBRATO_MAX_DELAY_MAX}
              step={VIBRATO_MAX_DELAY_STEP}
              unit={VIBRATO_MAX_DELAY_UNIT}
            />
            <SliderControlView
              name="vibrato"
              property="wet"
              label="Mezcla"
              value={effects.vibrato?.wet}
              handleChange={handleChange}
              min={VIBRATO_WET_MIN}
              max={VIBRATO_WET_MAX}
              step={VIBRATO_WET_STEP}
              unit={VIBRATO_WET_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="chorus"
        label="Coro"
        checked={effects.chorus?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="chorus"
              property="delayTime"
              label="Tiempo de Retardo"
              value={effects.chorus?.delayTime}
              handleChange={handleChange}
              min={CHORUS_DELAY_TIME_MIN}
              max={CHORUS_DELAY_TIME_MAX}
              step={CHORUS_DELAY_TIME_STEP}
              unit={CHORUS_DELAY_TIME_UNIT}
            />
            <SliderControlView
              name="chorus"
              property="depth"
              label="Profundidad"
              value={effects.chorus?.depth}
              handleChange={handleChange}
              min={CHORUS_DEPTH_MIN}
              max={CHORUS_DEPTH_MAX}
              step={CHORUS_DEPTH_STEP}
              unit={CHORUS_DEPTH_UNIT}
            />
            <SliderControlView
              name="chorus"
              property="feedback"
              label="Retroalimentación"
              value={effects.chorus?.feedback}
              handleChange={handleChange}
              min={CHORUS_FEEDBACK_MIN}
              max={CHORUS_FEEDBACK_MAX}
              step={CHORUS_FEEDBACK_STEP}
              unit={CHORUS_FEEDBACK_UNIT}
            />
            <SliderControlView
              name="chorus"
              property="frequency"
              label="Frecuencia"
              value={effects.chorus?.frequency}
              handleChange={handleChange}
              min={CHORUS_FREQUENCY_MIN}
              max={CHORUS_FREQUENCY_MAX}
              step={CHORUS_FREQUENCY_STEP}
              unit={CHORUS_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="chorus"
              property="spread"
              label="Propagación"
              value={effects.chorus?.spread}
              handleChange={handleChange}
              min={CHORUS_SPREAD_MIN}
              max={CHORUS_SPREAD_MAX}
              step={CHORUS_SPREAD_STEP}
              unit={CHORUS_SPREAD_UNIT}
            />
            <DropdownControlView
              name="chorus"
              property="type"
              label="Forma de Onda"
              value={effects.chorus?.type}
              handleChange={handleChange}
              options={[
                CHORUS_TYPE_SINE,
                CHORUS_TYPE_SQUARE,
                CHORUS_TYPE_TRIANGLE,
                CHORUS_TYPE_SAWTOOTH,
              ]}
            />
            <SliderControlView
              name="chorus"
              property="wet"
              label="Mezcla"
              value={effects.chorus?.wet}
              handleChange={handleChange}
              min={CHORUS_WET_MIN}
              max={CHORUS_WET_MAX}
              step={CHORUS_WET_STEP}
              unit={CHORUS_WET_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="tremolo"
        label="Tremolo"
        checked={effects.tremolo?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="tremolo"
              property="frequency"
              label="Frecuencia"
              value={effects.tremolo?.frequency}
              handleChange={handleChange}
              min={TREMOLO_FREQUENCY_MIN}
              max={TREMOLO_FREQUENCY_MAX}
              step={TREMOLO_FREQUENCY_STEP}
              unit={TREMOLO_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="tremolo"
              property="depth"
              label="Profundidad"
              value={effects.tremolo?.depth}
              handleChange={handleChange}
              min={TREMOLO_DEPTH_MIN}
              max={TREMOLO_DEPTH_MAX}
              step={TREMOLO_DEPTH_STEP}
              unit={TREMOLO_DEPTH_UNIT}
            />
            <SliderControlView
              name="tremolo"
              property="spread"
              label="Propagación"
              value={effects.tremolo?.spread}
              handleChange={handleChange}
              min={TREMOLO_SPREAD_MIN}
              max={TREMOLO_SPREAD_MAX}
              step={TREMOLO_SPREAD_STEP}
              unit={TREMOLO_SPREAD_UNIT}
            />
            <DropdownControlView
              name="tremolo"
              property="type"
              label="Forma de Onda"
              value={effects.tremolo?.type}
              handleChange={handleChange}
              options={[
                TREMOLO_TYPE_SINE,
                TREMOLO_TYPE_SQUARE,
                TREMOLO_TYPE_TRIANGLE,
                TREMOLO_TYPE_SAWTOOTH,
              ]}
            />
            <SliderControlView
              name="tremolo"
              property="wet"
              label="Mezcla"
              value={effects.tremolo?.wet}
              handleChange={handleChange}
              min={TREMOLO_WET_MIN}
              max={TREMOLO_WET_MAX}
              step={TREMOLO_WET_STEP}
              unit={TREMOLO_WET_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="delay"
        label="Retardo"
        checked={effects.delay?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="delay"
              property="delayTime"
              label="Tiempo de Retardo"
              value={effects.delay?.delayTime}
              handleChange={handleChange}
              min={DELAY_TIME_MIN}
              max={DELAY_TIME_MAX}
              step={DELAY_TIME_STEP}
              unit={DELAY_TIME_UNIT}
            />
            <SliderControlView
              name="delay"
              property="feedback"
              label="Retroalimentación"
              value={effects.delay?.feedback}
              handleChange={handleChange}
              min={DELAY_FEEDBACK_MIN}
              max={DELAY_FEEDBACK_MAX}
              step={DELAY_FEEDBACK_STEP}
              unit={DELAY_FEEDBACK_UNIT}
            />
            <SliderControlView
              name="delay"
              property="maxDelay"
              label="Retardo Máximo"
              value={effects.delay?.maxDelay}
              handleChange={handleChange}
              min={DELAY_MAX_DELAY_MIN}
              max={DELAY_MAX_DELAY_MAX}
              step={DELAY_MAX_DELAY_STEP}
              unit={DELAY_MAX_DELAY_UNIT}
            />
            <SliderControlView
              name="delay"
              property="wet"
              label="Mezcla"
              value={effects.delay?.wet}
              handleChange={handleChange}
              min={DELAY_WET_MIN}
              max={DELAY_WET_MAX}
              step={DELAY_WET_STEP}
              unit={DELAY_WET_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="phaser"
        label="Phaser"
        checked={effects.phaser?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="phaser"
              property="frequency"
              label="Frecuencia"
              value={effects.phaser?.frequency}
              handleChange={handleChange}
              min={PHASER_FREQUENCY_MIN}
              max={PHASER_FREQUENCY_MAX}
              step={PHASER_FREQUENCY_STEP}
              unit={PHASER_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="phaser"
              property="octaves"
              label="Octavas"
              value={effects.phaser?.octaves}
              handleChange={handleChange}
              min={PHASER_OCTAVES_MIN}
              max={PHASER_OCTAVES_MAX}
              step={PHASER_OCTAVES_STEP}
              unit={PHASER_OCTAVES_UNIT}
            />
            <SliderControlView
              name="phaser"
              property="stages"
              label="Etapas"
              value={effects.phaser?.stages}
              handleChange={handleChange}
              min={PHASER_STAGES_MIN}
              max={PHASER_STAGES_MAX}
              step={PHASER_STAGES_STEP}
              unit={PHASER_STAGES_UNIT}
            />
            <SliderControlView
              name="phaser"
              property="Q"
              label="Resonancia (Q)"
              value={effects.phaser?.Q}
              handleChange={handleChange}
              min={PHASER_Q_MIN}
              max={PHASER_Q_MAX}
              step={PHASER_Q_STEP}
              unit={PHASER_Q_UNIT}
            />
            <SliderControlView
              name="phaser"
              property="baseFrequency"
              label="Frecuencia Base"
              value={effects.phaser?.baseFrequency}
              handleChange={handleChange}
              min={PHASER_BASE_FREQUENCY_MIN}
              max={PHASER_BASE_FREQUENCY_MAX}
              step={PHASER_BASE_FREQUENCY_STEP}
              unit={PHASER_BASE_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="phaser"
              property="wet"
              label="Mezcla"
              value={effects.phaser?.wet}
              handleChange={handleChange}
              min={PHASER_WET_MIN}
              max={PHASER_WET_MAX}
              step={PHASER_WET_STEP}
              unit={PHASER_WET_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="eq3"
        label="Ecualizador"
        checked={effects.eq3?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="eq3"
              property="low"
              label="Bajos"
              value={effects.eq3?.low}
              handleChange={handleChange}
              min={EQ3_LOW_MIN}
              max={EQ3_LOW_MAX}
              step={EQ3_LOW_STEP}
              unit={EQ3_LOW_UNIT}
            />
            <SliderControlView
              name="eq3"
              property="mid"
              label="Medios"
              value={effects.eq3?.mid}
              handleChange={handleChange}
              min={EQ3_MID_MIN}
              max={EQ3_MID_MAX}
              step={EQ3_MID_STEP}
              unit={EQ3_MID_UNIT}
            />
            <SliderControlView
              name="eq3"
              property="high"
              label="Agudos"
              value={effects.eq3?.high}
              handleChange={handleChange}
              min={EQ3_HIGH_MIN}
              max={EQ3_HIGH_MAX}
              step={EQ3_HIGH_STEP}
              unit={EQ3_HIGH_UNIT}
            />
            <SliderControlView
              name="eq3"
              property="lowFrequency"
              label="Frecuencia Baja (Hz)"
              value={effects.eq3?.lowFrequency}
              handleChange={handleChange}
              min={EQ3_LOW_FREQUENCY_MIN}
              max={EQ3_LOW_FREQUENCY_MAX}
              step={EQ3_LOW_FREQUENCY_STEP}
              unit={EQ3_LOW_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="eq3"
              property="highFrequency"
              label="Frecuencia Alta (Hz)"
              value={effects.eq3?.highFrequency}
              handleChange={handleChange}
              min={EQ3_HIGH_FREQUENCY_MIN}
              max={EQ3_HIGH_FREQUENCY_MAX}
              step={EQ3_HIGH_FREQUENCY_STEP}
              unit={EQ3_HIGH_FREQUENCY_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="compressor"
        label="Compresor"
        checked={effects.compressor?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="compressor"
              property="threshold"
              label="Umbral (dB)"
              value={effects.compressor?.threshold}
              handleChange={handleChange}
              min={COMPRESSOR_THRESHOLD_MIN}
              max={COMPRESSOR_THRESHOLD_MAX}
              step={COMPRESSOR_THRESHOLD_STEP}
              unit={COMPRESSOR_THRESHOLD_UNIT}
            />
            <SliderControlView
              name="compressor"
              property="ratio"
              label="Relación"
              value={effects.compressor?.ratio}
              handleChange={handleChange}
              min={COMPRESSOR_RATIO_MIN}
              max={COMPRESSOR_RATIO_MAX}
              step={COMPRESSOR_RATIO_STEP}
              unit={COMPRESSOR_RATIO_UNIT}
            />
            <SliderControlView
              name="compressor"
              property="attack"
              label="Ataque (s)"
              value={effects.compressor?.attack}
              handleChange={handleChange}
              min={COMPRESSOR_ATTACK_MIN}
              max={COMPRESSOR_ATTACK_MAX}
              step={COMPRESSOR_ATTACK_STEP}
              unit={COMPRESSOR_ATTACK_UNIT}
            />
            <SliderControlView
              name="compressor"
              property="release"
              label="Liberación (s)"
              value={effects.compressor?.release}
              handleChange={handleChange}
              min={COMPRESSOR_RELEASE_MIN}
              max={COMPRESSOR_RELEASE_MAX}
              step={COMPRESSOR_RELEASE_STEP}
              unit={COMPRESSOR_RELEASE_UNIT}
            />
            <SliderControlView
              name="compressor"
              property="knee"
              label="Rodilla (dB)"
              value={effects.compressor?.knee}
              handleChange={handleChange}
              min={COMPRESSOR_KNEE_MIN}
              max={COMPRESSOR_KNEE_MAX}
              step={COMPRESSOR_KNEE_STEP}
              unit={COMPRESSOR_KNEE_UNIT}
            />
          </>
        }
      />
      <EffectControlView
        name="autoWah"
        label="Auto Wah"
        checked={effects.autoWah?.enabled}
        handleChange={handleChange}
        controls={
          <>
            <SliderControlView
              name="autoWah"
              property="baseFrequency"
              label="Frecuencia Base (Hz)"
              value={effects.autoWah?.baseFrequency}
              handleChange={handleChange}
              min={AUTOWAH_BASE_FREQUENCY_MIN}
              max={AUTOWAH_BASE_FREQUENCY_MAX}
              step={AUTOWAH_BASE_FREQUENCY_STEP}
              unit={AUTOWAH_BASE_FREQUENCY_UNIT}
            />
            <SliderControlView
              name="autoWah"
              property="octaves"
              label="Octavas"
              value={effects.autoWah?.octaves}
              handleChange={handleChange}
              min={AUTOWAH_OCTAVES_MIN}
              max={AUTOWAH_OCTAVES_MAX}
              step={AUTOWAH_OCTAVES_STEP}
              unit={AUTOWAH_OCTAVES_UNIT}
            />
            <SliderControlView
              name="autoWah"
              property="sensitivity"
              label="Sensibilidad (dB)"
              value={effects.autoWah?.sensitivity}
              handleChange={handleChange}
              min={AUTOWAH_SENSITIVITY_MIN}
              max={AUTOWAH_SENSITIVITY_MAX}
              step={AUTOWAH_SENSITIVITY_STEP}
              unit={AUTOWAH_SENSITIVITY_UNIT}
            />
            <SliderControlView
              name="autoWah"
              property="Q"
              label="Resonancia (Q)"
              value={effects.autoWah?.Q}
              handleChange={handleChange}
              min={AUTOWAH_Q_MIN}
              max={AUTOWAH_Q_MAX}
              step={AUTOWAH_Q_STEP}
              unit={AUTOWAH_Q_UNIT}
            />
            <SliderControlView
              name="autoWah"
              property="gain"
              label="Ganancia (dB)"
              value={effects.autoWah?.gain}
              handleChange={handleChange}
              min={AUTOWAH_GAIN_MIN}
              max={AUTOWAH_GAIN_MAX}
              step={AUTOWAH_GAIN_STEP}
              unit={AUTOWAH_GAIN_UNIT}
            />
            <SliderControlView
              name="autoWah"
              property="follower"
              label="Seguidor"
              value={effects.autoWah?.follower}
              handleChange={handleChange}
              min={AUTOWAH_FOLLOWER_MIN}
              max={AUTOWAH_FOLLOWER_MAX}
              step={AUTOWAH_FOLLOWER_STEP}
              unit={AUTOWAH_FOLLOWER_UNIT}
            />
            <SliderControlView
              name="autoWah"
              property="wet"
              label="Mezcla"
              value={effects.autoWah?.wet}
              handleChange={handleChange}
              min={AUTOWAH_WET_MIN}
              max={AUTOWAH_WET_MAX}
              step={AUTOWAH_WET_STEP}
              unit={AUTOWAH_WET_UNIT}
            />
          </>
        }
      />{" "} */}
    </>
  );
}
